### ISSUE TITLE
请问表格的训练数据在哪里下载？谢谢

### ISSUE THREAD

**Issue by norainnosun** [yangjian940712/ocr-table-ssd#1]

**Comment by norainnosun** [comment]
训练数据是否是保密？能否发一份呢，谢谢

**Comment by hanson-young** [comment]
表格的数据是公司的，标注方法就是标注表格单元的线段，可以粗略的标注，比如标注每个单元格的顶点然后自动生成mask标签

**Comment by norainnosun** [comment]
感谢回复，我用labelme标注，是否一个单元格要标注四条线段?，总共的训练集大约需要多少呢？标注的结果如下：

![label](https://user-images.githubusercontent.com/66993916/84970017-6fd3be00-b14c-11ea-988e-12245d72dedf.png)
![label_viz](https://user-images.githubusercontent.com/66993916/84970396-3059a180-b14d-11ea-8090-9ca60c5245db.png)

还有两个问题需请教一下：
1、JNetV3是否是mobilenet unet呢，imJNetV3大概是做了什么改进呢，是否有参考资料之类的
2、训练的时候先训练segmentation分支，除了将train_ssd中143行的loss改为144行的segmentation_loss，还有其他需要修改的地方吗
3、我看您训练出的heatmap结果挺好的，是否还有必要进行ssd检测，可否直接处理heatmap用霍夫变换检测直线的方式找出对应的表格框？谢谢
![heatmap](https://user-images.githubusercontent.com/66993916/84971234-da85f900-b14e-11ea-9743-90b3f91e26fa.png)

**Comment by hanson-young** [comment]
1、是的
2、代码没整理的很好，时间有点久，可能你需要再检查下SSD主干网络部分，那块我在预测的时候做了houghline和旋转
3、表格格式化的工作可以用多种方式，可以直接用houghline。我另一个目的是为了和原生的ssd做比较

**Comment by norainnosun** [comment]
好的，感谢！
